lucko/helper

- helper-profiles/src/main/java/me/lucko/helper/profiles/plugin/ProfilesPlugin.java
Simple correction of string encapsulation from `string` to 'string' in collection lookup functions that currently breaks the SQL query.
> String encapsulation from `string` to 'string' in collection functions

- helper/src/main/java/me/lucko/helper/gson/typeadapters/GsonSerializableAdapterFactory.java
If GsonSerializable is null, GsonSerializableAdapterFactory throws NullPointerException.
You can reproduce using following code.
```java
public static void test() {
String json = GsonProvider.standard().toJson(new SerializeTest());
System.out.println(json);
SerializeTest serializeTest = GsonProvider.standard().fromJson(json, SerializeTest.class);
System.out.println(serializeTest.position);
}
public static class SerializeTest {
public Position position = null;
}
```
> Fix null GsonSerializable

- helper-sql/pom.xml
- helper-sql/src/main/java/me/lucko/helper/sql/BatchBuilder.java
- helper-sql/src/main/java/me/lucko/helper/sql/Sql.java
- helper-sql/src/main/java/me/lucko/helper/sql/plugin/HelperSql.java
- helper-sql/src/main/java/me/lucko/helper/sql/plugin/HelperSqlBatchBuilder.java
- helper-sql/src/main/java/me/lucko/helper/sql/plugin/HelperSqlPlugin.java
- helper-sql/src/main/java/me/lucko/helper/sql/util/ThrownConsumer.java
- helper-sql/src/main/java/me/lucko/helper/sql/util/ThrownFunction.java
Adds a number of convenience methods and a couple of configuration updates.
Namely, the settings in the implementation provided by `HelperSql` have been made into Constants for ease of viewing and access for downstream consumers/forks to make modifications or understand the default configurations.
In addition, two configurations have been added entirely:
**useConfigs=maxPerformance**:
Connector/J has a setting which implies a number of configuration modifications behind `maxPerformance`. It's a little unclear whether or not they're applied to `mariadb-java-client`, but the addition can't hurt. You can view more information about this setting [from this article](http://assets.en.oreilly.com/1/event/21/Connector_J%20Performance%20Gems%20Presentation.pdf).
**maximumPoolSize**:
I believe this …
> HelperSql: Convenience methods, config updates.

- helper/src/main/java/me/lucko/helper/menu/Gui.java
You would think that InventoryCloseEvent would be sufficient, however a moderator on our server discovered it's possible to dupe items by exploiting a glitch in which helper believes a previous menu is still active.
https://www.youtube.com/watch?v=rKJPrAelml8
The fix for this is just to invalidate the menu on PlayerDeathEvent, as well.
EDIT: There was another dupe glitch discovered which was rectified in the same manner: Invaliding the GUI on PlayerChangedWorldEvent and PlayerTeleportEvent.
PlayerTeleportEvent turned out to be the catalyst, however I've left PlayerChangedWorldEvent as it didn't seem to cause any additional issues, and I'd rather not take it out in the off-chance an enterprising player discovered another way to mess with it.
Here's the video for the update: …
> Invalidate Guis on PlayerDeathEvent

- helper/src/main/java/me/lucko/helper/gson/typeadapters/BukkitSerializableAdapterFactory.java
Both `STANDARD_GSON` and `PRETTY_PRINT_GSON` from GsonProvider are building with `serializeNulls` and, as such, the TypeAdapter for ConfigurationSerializable should be able to handle reading and writing null values.
> Allow null read/write values for ConfigurationSerializable

- helper/src/main/java/me/lucko/helper/menu/Gui.java
Prefacing, this doesn't break the menu and doesn't allow for duping. However, it's possible to lose items permanently.
I've had a video made to show how to duplicate this bug, but I have confirmed that this PR will fix it.
https://youtu.be/9sZJhH6cvW8
To explain the bug:
1. Put yourself into a situation where your inventory can be closed automatically with some kind of delay.
- In the video, this is done via being pushed by water.
2. Put an ItemStack on your cursor.
3. Wait for your inventory to be closed automatically.
- Despite the inventory having been closed, the ItemStack still exists on your cursor.
4. Open a menu without opening your player inventory
- In the video, this is done via right-clicking a Gui-opening robot.
5. Drag the items around in the inventory.
The problem is that …
> Fix ability to drag (and lose) items in menus

- helper/src/main/java/me/lucko/helper/menu/Gui.java
It's possible to get your inventory into a floating state where multiple virtual "inventories" are active.
This doesn't directly solve that issue, but ensures that no actions are run if the clicked inventory is not the Helper GUI.
> 1.8-specific floating inventory fix.

- helper/src/main/java/me/lucko/helper/menu/Gui.java
On `InventoryCloseEvent`, always invalidate the GUI if it's still valid and then only continue on if the inventory being closed is the GUI.
On `InventoryOpenEvent`, if the inventory that is being opened is not the GUI and the GUI is valid, invalidate it.
> Ensure GUI invalidation on InventoryOpenEvent and InventoryCloseEvent

- helper/src/main/java/me/lucko/helper/maven/LibraryLoader.java
- helper/src/main/java/me/lucko/helper/maven/MavenLibrary.java
As of January 15th this year, maven central does no longer support http urls. Therefore downloading artifacts via http will fail.
Read more about it here: https://support.sonatype.com/hc/en-us/articles/360041287334
> Replace http urls with https

- helper/src/main/java/me/lucko/helper/menu/DummySlot.java
- helper/src/main/java/me/lucko/helper/menu/Gui.java
This glitch was reported to me today, and this fix was implemented. However, I feel as though there is likely a better way to implement this fix so I am very open to criticisms and suggestions.
It seems as though there are some instances where a Gui can have items applied to it, even after that Gui has been invalidated. Because the Gui has been invalidated, it isn't listening and, thus, items can be pulled from the inventory.
In [this video](https://youtu.be/OsTdpfDSaX0), you can see this in action. The piston pushing the player seems to call for Gui invalidation. Because the menu is loading player heads, it's done on a scheduler and then placed in the Gui. Even though the Scheduler is bound to the Gui, the method which places them into it are still called.
The Gui attempts to close, but …
> Fix Gui getting slots after invalidation

- helper/src/main/java/me/lucko/helper/hologram/individual/PacketIndividualHologramFactory.java
Certain packets, such as Entity Equipment, Entity Metadata or Update Tile Entity, share the same instance when they are sent by the server. For such packets, metadata in this case, only the last written change will be preserved. Thus, the packet receiver will only see what the last written change was.
The solution is to clone the packet before modification.
> Fix clashing HologramLines

- helper/src/main/java/me/lucko/helper/hologram/BukkitHologramFactory.java
Paper introduces `ArmorStand#setCanTick(boolean)` to the ArmorStand object, which is a great performance improvement, especially when using a LOT of holograms.
This PR checks if that method exists and, if it does, uses it.
There exists the tiniest overhead in calling a reflected method, but it only happens when ArmorStand objects are actually created, so its affects are entirely negligible.
Have tested thoroughly to ensure that setCanTick doesn't negatively affect hologram's current functions at all.
> Use setCanTick on Hologram ArmorStands when available

- helper/src/main/java/me/lucko/helper/command/functional/FunctionalCommandBuilderImpl.java
This just fixes an issue where it checks for the `permission` field to not be null instead of the actual `description` parameter. Basically if you didn't set up a permission before setting a description, it throws!
> Check for description null instead of permission.

- helper/src/main/java/me/lucko/helper/hologram/BaseHologram.java
- helper/src/main/java/me/lucko/helper/hologram/BukkitHologramFactory.java
- helper/src/main/java/me/lucko/helper/hologram/individual/PacketIndividualHologramFactory.java
Currently, setClickCallback doesn't work (at least for BukkitHologramFactory.BukkitHologram).
I'm going to be making a PR soon which will fix this, but for now, this is part of my hotfix, as I needed something quicker than I could implement the fix.
```java
private static final Field SPAWNED_ENTITIES_FIELD;
static {
Field spawnedEntitiesField = null;
try {
Class<?> clazz = Class.forName("me.lucko.helper.hologram.BukkitHologramFactory$BukkitHologram");
spawnedEntitiesField = clazz.getDeclaredField("spawnedEntities");
spawnedEntitiesField.setAccessible(true);
} catch (Throwable e) {
e.printStackTrace();
}
SPAWNED_ENTITIES_FIELD = spawnedEntitiesField;
}
private List<UUID> getHologramEntityIds(Hologram hologram) {
try {
return ((List<ArmorStand>) …
```
> Expose Hologram ArmorStands

- helper/src/main/java/me/lucko/helper/hologram/BukkitHologramFactory.java
Holograms which use `HologramFactory` (which, by default, delegates to the `BukkitHologramFactory`), stopped working at some point. The issue seems to be that Bukkit/Spigot no longer fires the requisite events on invisible ArmorStand objects.
My fix for this is simple: When a Hologram is clickable, spawn Pigs as passenger for the ArmorStands, and listen to those, instead.
From all the testing I've done, I also believe that `IndividualHologramFactory` is no longer working, as well. However, given this relies on packets and packet listening, rather than events, I'm honestly not entirely certain why this would be and am much more hesitant to work on a fix for it. Additionally, given I don't use it, I have very little motivation, for which I apologize.
If anyone wants to tackle that, please …
> Fix clickable holograms for BukkitHologramFactory

- helper/src/main/java/me/lucko/helper/serialize/VectorPoint.java
`VectorPoint` has a `toLocation(World)` method which, when called, will cache and return a `Location` object. However, subsequent calls of `toLocation(World)` will always return the `Location` object cached in the first call, regardless of whether or not the supplied `World` has changed.
There were a number of possible solutions to this:
1. Don't cache the `Location` object at all.
2. Create a `Map<String, Location>` cache which uses the `World#getName()` value to lookup cached results.
3. Re-cache the `Location` object if the supplied `World` is different.
I opted for option 3 because it would have the least impact on performance with the least code changes.
> Fix VectorPoint returning incorrect Location for supplied World parameter

- helper-sql/src/main/java/me/lucko/helper/sql/plugin/HelperSqlPlugin.java
- helper/src/main/java/me/lucko/helper/maven/LibraryLoader.java
- helper/src/main/java/me/lucko/helper/maven/MavenLibraries.java
- helper/src/main/java/me/lucko/helper/maven/MavenLibrary.java
- helper/src/main/java/me/lucko/helper/maven/Repository.java
- helper/src/main/java/me/lucko/helper/maven/URLInjector.java
- helper/src/main/java/me/lucko/helper/maven/UnsafeInserter.java
- helper/src/main/java/me/lucko/helper/maven/UnsafeURLInjector.java
Since the Maven library features in helper are deemed broken on Java 16+, this PR adapts and utilizes [SlimJar's UnsafeInjectable](https://github.com/slimjar/slimjar/blob/master/slimjar/src/main/java/io/github/slimjar/injector/loader/UnsafeInjectable.java) to inject URLs into URLClassLoaders using sun.misc.Unsafe. This solution works well on Java 9+ and can be used to get the API to work again.
**Side implementation note**: UnsafeURLInjector _only_ works on Java 9+. [While it is possible to make it work for Java 8 by replacing ArrayDeque with a generic Collection, and use `urls` as the field name for Java 8](https://github.com/lucko/helper/commit/e9efc940d84b5fb41cc9ffe4310e4fe7b839674f#diff-0519ea5ff66bca2a00d92b1b85fd8e019c40732df9fe0715fffcbfe30fcb38ddR34), I believe this is …
> Use sun.misc.Unsafe to inject URLs into ClassLoaders on Java 9+

- helper-redis/pom.xml
- helper-redis/src/main/java/me/lucko/helper/redis/plugin/HelperRedis.java
- helper-redis/src/main/java/me/lucko/helper/redis/plugin/HelperRedisPlugin.java
helper-redis has a race condition where channels are subscribed to each on their own thread, while the underlying Jedis instance is not thread safe. This is problematic as the confirmations of each subscription can interfere with each other, preventing it being read correctly. While helper-redis is able to recover most of the time, sometimes it can prevent some or all channels from functioning.
This PR adds a ReentrantLock to each instance of `subscribe` and `unsubscribe`, which prevents this from happening.
I have also updated the jedis version, bumped the package version, and removed some redundant code.
> Fix helper-redis race condition

- helper/pom.xml
- helper/src/main/java/me/lucko/helper/scoreboard/PacketScoreboardTeam.java
1.17 introduced some changes to the protocol. This code addresses the changes and fixes PacketScoreboard on 1.17 and (hopefully) later.
> Fix PacketScoreboard for 1.17

- helper/src/main/java/me/lucko/helper/time/DurationFormatter.java
I debated deprecating the existing enumeration support, but I don't think it's necessary as they still serve a convenience purpose and help improve code clarity most the time.
I did run the following highly professional _unit_ tests to confirm functionality:
```
System.out.println("CTest 1: " + DurationFormatter.format(Duration.of(1337420, ChronoUnit.SECONDS), true, 1));
System.out.println("CTest 2: " + DurationFormatter.format(Duration.of(1337420, ChronoUnit.SECONDS), true, 2));
System.out.println("CTest 3: " + DurationFormatter.format(Duration.of(1337420, ChronoUnit.SECONDS), true, 3));
System.out.println("CTest 4: " + DurationFormatter.format(Duration.of(1337420, ChronoUnit.SECONDS), true, 4));
System.out.println("CTest 5: " + DurationFormatter.format(Duration.of(1337420, …
```
> Rework DurationFormatter to allow for more abstract implementations

- helper/src/main/java/me/lucko/helper/terminable/composite/AbstractCompositeTerminable.java
- helper/src/main/java/me/lucko/helper/terminable/composite/AbstractWeakCompositeTerminable.java
I'm unsure why exactly `isClosed()` was not implemented, but this PR implements it and makes it behave as expected when closing CompositeTerminables generated from CompositeTerminable.create()
> Implement isClosed in Abstract(Weak)CompositeTerminable
